name: Auto Update EPG

on:
  schedule:
    - cron: '0 3 * * *'  # каждый день в 03:00 UTC
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download epg2.xml
        run: curl -s -o epg2.xml http://epg.one/epg2.xml

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if [[ `git status --porcelain` ]]; then
            git add epg2.xml
            git commit -m "Auto-update epg2.xml"
            git push
          else
            echo "No changes"
