name: Update EPG File

on:
  schedule:
    - cron: '0 * * * *'  # Обновление каждый час
  push:
    branches:
      - main

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git configuration
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Download EPG file
      run: |
        wget https://epg.one/epg2.xml -O epg2.xml

    - name: Commit and Push changes using Personal Access Token
      run: |
        git remote set-url origin https://<your-username>:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
        git add epg2.xml
        git commit -m "Обновление EPG файла" || echo "No changes to commit"
        git push
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
