name: Update EPG File

on:
  schedule:
    - cron: '0 * * * *'  # Обновление каждый час
  push:
    branches:
      - main

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download EPG file
      run: |
        wget https://epg.one/epg2.xml -O epg2.xml

    - name: Set up GitHub credentials
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "GitHub Actions"

    - name: Commit and Push changes
      run: |
        git add epg2.xml
        git commit -m "Обновление EPG файла"
        git push https://github.com/${{ github.repository }}.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
