name: Update EPG File

on:
  schedule:
    - cron: '0 * * * *'  # обновление каждый час
  push:
    branches:
      - main

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests gitpython

    - name: Download EPG file
      run: |
        python download_epg.py
