name: Update EPG

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # кожні 6 годин

jobs:
  update-epg:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Set remote with PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/bvaflek/iptv-mirror.git

      - name: Update EPG file
        run: |
          git add epg2.xml
          git diff --cached --quiet || git commit -m "Обновление EPG файла"
          git push
